x-db_environment: &db_environment
  environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_DB
    - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable

services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "3737:3737"
    <<: *db_environment
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    <<: *db_environment

volumes:
  dbdata:
